[package]
name = "pipelining-macro"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/alexander-novo/pipelining-macro"
license = "MIT"
license-file = "LICENSE"
keywords = ["convenience", "syntax"]
categories = ["no-std", "rust-patterns"]

[dev-dependencies]
paste = "1.0.15"
